"""spec_aligned_initial_schema

Revision ID: 0a7dfe8320d0
Revises:
Create Date: 2026-03-21 20:26:40.381890

Baseline schema aligned with docs/SPEC.md: clients, booking_media, weekly_schedules,
availability_exceptions, bookings with client_id and optional media + client_note,
slots without per-row price (PriceEntry drives display), FK from slots.source_template_id.

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0a7dfe8320d0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('availability_exceptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('start', sa.DateTime(), nullable=False),
    sa.Column('end', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('booking_media',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('media_type', sa.Enum('current_hairstyle', 'inspiration', name='mediatype', native_enum=False), nullable=False),
    sa.Column('file_name', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('marketing_opt_in', sa.Boolean(), server_default=sa.text("0"), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_table('salons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=512), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.Enum('haircut', 'haircut_hairdressing', 'color', name='servicetype', native_enum=False), nullable=False),
    sa.Column('gender', sa.Enum('male', 'female', name='gender', native_enum=False), nullable=False),
    sa.Column('base_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('at_home_buffer_minutes', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'gender', name='uq_service_type_gender')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('weekly_schedules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('open_time', sa.Time(), nullable=False),
    sa.Column('close_time', sa.Time(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_of_week', name='uq_weekly_schedules_day')
    )
    op.create_table('weekly_templates',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('price_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_entries_service_id'), 'price_entries', ['service_id'], unique=False)
    op.create_table('slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_available', sa.Boolean(), server_default=sa.text("1"), nullable=False),
    sa.Column('source_template_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_template_id'], ['weekly_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('template_slots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['weekly_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slot_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('price_at_booking', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('salon_address_at_booking', sa.Text(), nullable=False),
    sa.Column('location', sa.Enum('salon', 'home', name='location', native_enum=False), nullable=False),
    sa.Column('home_address', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('confirmed', 'edited', 'cancelled', name='bookingstatus', native_enum=False), nullable=False),
    sa.Column('edit_token', sa.String(length=64), nullable=False),
    sa.Column('client_note', sa.Text(), nullable=True),
    sa.Column('current_hairstyle_media_id', sa.Integer(), nullable=True),
    sa.Column('inspiration_media_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['current_hairstyle_media_id'], ['booking_media.id'], name='fk_bookings_current_hairstyle_media'),
    sa.ForeignKeyConstraint(['inspiration_media_id'], ['booking_media.id'], name='fk_bookings_inspiration_media'),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['slot_id'], ['slots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('edit_token', name='uq_bookings_edit_token'),
    sa.UniqueConstraint('slot_id')
    )
    op.create_index(op.f('ix_bookings_client_id'), 'bookings', ['client_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_bookings_client_id'), table_name='bookings')
    op.drop_table('bookings')
    op.drop_table('template_slots')
    op.drop_table('slots')
    op.drop_index(op.f('ix_price_entries_service_id'), table_name='price_entries')
    op.drop_table('price_entries')
    op.drop_table('weekly_templates')
    op.drop_table('weekly_schedules')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('services')
    op.drop_table('salons')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_table('booking_media')
    op.drop_table('availability_exceptions')
    # ### end Alembic commands ###
